#!/usr/bin/env python3
"""md3 build tracker: check, sync, report, next.

Reads the batch files in docs/plan/, the decision IDs in docs/DECISIONS.md
and the commit trailers in git, and generates docs/STATUS.md and
docs/TIMELINE.md from them. Standard library only.

Usage: python3 tools/track.py {check,sync,report,next,msg FILE} [--root DIR]
"""

from __future__ import annotations

import argparse
import os
import re
import subprocess
import sys
from dataclasses import dataclass, field
from pathlib import Path

PLAN_DIR = Path("docs/plan")
DECISIONS = Path("docs/DECISIONS.md")
STATUS = Path("docs/STATUS.md")
TIMELINE = Path("docs/TIMELINE.md")

TASK_ID = re.compile(r"^B(\d+)\.(\d+)\.(\d+)([a-z]?)$")
STAGE_ID = re.compile(r"^B(\d+)\.(\d+)$")
BATCH_ID = re.compile(r"^B(\d+)$")
X_ID = re.compile(r"^X\d+$")
STATUS_RE = re.compile(r"^(todo|doing|review|done|blocked: \S.*|dropped: \S.*)$")
BATCH_FILE = re.compile(r"^B(\d{2})-[a-z0-9-]+\.md$")
TRAILER = re.compile(r"^([A-Za-z][A-Za-z-]*): (.*)$")

# Security rule 10: no AI attribution. Tooling file names are allowed.
ATTRIBUTION_ALLOWED = ("CLAUDE.md", ".claude/")
ATTRIBUTION = re.compile(
    r"co-authored-by|claude|anthropic|generated (with|by)|\U0001F916", re.IGNORECASE
)

GENERATED_MARK = "<!-- generated by tools/track.py sync at "
SECOND_OPINION = {"B1", "B3"}  # batches whose cross-check also needs a second AI model
EMPTY = "·"


class TrackError(Exception):
    pass


# ---------------------------------------------------------------- parsing


@dataclass
class Task:
    id: str
    name: str
    decisions: str
    depends: list[str]
    done_when: str
    status: str
    stage: str
    file: str
    line: int


@dataclass
class Stage:
    id: str
    name: str
    tasks: list[Task] = field(default_factory=list)


@dataclass
class Batch:
    id: str
    name: str
    file: str
    stages: list[Stage] = field(default_factory=list)
    notes: list[str] = field(default_factory=list)

    @property
    def tasks(self) -> list[Task]:
        return [t for s in self.stages for t in s.tasks]


@dataclass
class Plan:
    batches: list[Batch]
    backlog_ids: set[str]
    errors: list[str]

    @property
    def tasks(self) -> list[Task]:
        return [t for b in self.batches for t in b.tasks]

    def task(self, tid: str) -> Task | None:
        return next((t for t in self.tasks if t.id == tid), None)


def split_row(line: str) -> list[str]:
    return [c.strip() for c in line.strip().strip("|").split("|")]


def parse_plan(root: Path) -> Plan:
    errors: list[str] = []
    batches: list[Batch] = []
    plan_dir = root / PLAN_DIR
    if not plan_dir.is_dir():
        raise TrackError(f"{PLAN_DIR} not found")
    for path in sorted(plan_dir.iterdir()):
        m = BATCH_FILE.match(path.name)
        if not m:
            continue
        rel = str(PLAN_DIR / path.name)
        batch_num = int(m.group(1))
        batch: Batch | None = None
        stage: Stage | None = None
        in_notes = False
        for n, line in enumerate(read_plain(path).splitlines(), 1):
            if in_notes and line.startswith("- ") and batch is not None:
                batch.notes.append(line[2:].strip())
            if line.startswith("# "):
                hm = re.match(r"^# (B\d+) (.+)$", line)
                if not hm or hm.group(1) != f"B{batch_num}":
                    errors.append(f"{rel}:{n}: batch heading must be '# B{batch_num} <name>'")
                    continue
                batch = Batch(hm.group(1), hm.group(2).strip(), rel)
            elif line.startswith("## "):
                title = line[3:].strip()
                in_notes = title == "Notes"
                if in_notes:
                    stage = None
                    continue
                sid, _, name = title.partition(" ")
                if not STAGE_ID.match(sid) or batch is None or not sid.startswith(batch.id + "."):
                    errors.append(f"{rel}:{n}: malformed stage heading '{title}'")
                    stage = None
                    continue
                stage = Stage(sid, name.strip())
                batch.stages.append(stage)
            elif line.startswith("| ") and stage is not None:
                cells = split_row(line)
                if cells[0] in ("ID",) or set(cells[0]) <= {"-"}:
                    continue
                if len(cells) != 6:
                    errors.append(f"{rel}:{n}: task row needs 6 columns, has {len(cells)}")
                    continue
                tid, name, decisions, deps, done_when, status = cells
                deps_list = [] if deps in ("—", "-", "") else [d.strip() for d in deps.split(",")]
                stage.tasks.append(
                    Task(tid, name, decisions, deps_list, done_when, status, stage.id, rel, n)
                )
        if batch is None:
            errors.append(f"{rel}: no batch heading")
        else:
            batches.append(batch)
    backlog_ids: set[str] = set()
    backlog = plan_dir / "BACKLOG.md"
    if backlog.exists():
        for line in read_plain(backlog).splitlines():
            if line.startswith("| X"):
                backlog_ids.add(split_row(line)[0])
    return Plan(batches, backlog_ids, errors)


@dataclass
class DecisionIndex:
    active: set[str]
    superseded: set[str]
    text: str


def decision_index(root: Path) -> DecisionIndex:
    """Numbered decisions are defined by a table row whose first cell is the
    number (e.g. '| ✅ 102 |', '| 22 |', '| ✅ 32 / 56 |') or by a heading
    ('#### #76a ...'). A row marked ⛔ defines a superseded decision. Mere
    mentions of '#N' in running text define nothing."""
    text = read_plain(root / DECISIONS)
    active: set[str] = set()
    retired: set[str] = set()
    for line in text.splitlines():
        if line.startswith("|"):
            cell = split_row(line)[0]
            first = re.sub(r"[~*✅⛔🟡\s]", "", cell)
            for part in re.split(r"[,/]", first):
                if re.fullmatch(r"\d+[a-z]?", part):
                    (retired if "⛔" in cell else active).add(part)
        else:
            m = re.match(r"^#{2,4} #(\d+[a-z]?)\b", line)
            if m:
                active.add(m.group(1))
    return DecisionIndex(active, retired - active, text)


def decision_refs(cell: str) -> list[str]:
    return re.findall(r"#\d+[a-z]?|\bD\d+\b|\bV\d+\b|\bM0-\d+\b|§\d+(?:\.\d+)?", cell)


def decision_exists(ref: str, nums: set[str], text: str) -> bool:
    if ref.startswith("#"):
        return ref[1:] in nums
    if ref.startswith("§"):
        sec = re.escape(ref[1:])
        return re.search(rf"^#{{2,3}} {sec}[. ]", text, re.MULTILINE) is not None
    return re.search(rf"\b{re.escape(ref)}\b", text) is not None


# -------------------------------------------------------------------- git


def git(root: Path, *args: str) -> str:
    out = subprocess.run(
        ["git", *args], cwd=root, capture_output=True, text=True, encoding="utf-8"
    )
    if out.returncode != 0:
        raise TrackError(f"git {' '.join(args)} failed: {out.stderr.strip()}")
    return out.stdout


@dataclass
class Commit:
    sha: str
    date: str
    subject: str
    message: str
    parents: list[str]
    trailers: dict[str, str]

    @property
    def short(self) -> str:
        return self.sha[:7]

    @property
    def is_merge(self) -> bool:
        return len(self.parents) > 1


def parse_trailers(message: str) -> dict[str, str]:
    paragraphs = [p for p in re.split(r"\n\s*\n", message.strip()) if p.strip()]
    if len(paragraphs) < 2:
        return {}
    trailers: dict[str, str] = {}
    last: str | None = None
    for line in paragraphs[-1].splitlines():
        if line[:1] in (" ", "\t") and last is not None:  # continuation line
            trailers[last] = f"{trailers[last]} {line.strip()}"
            continue
        m = TRAILER.match(line.strip())
        if not m:
            return {}
        key = m.group(1).title()  # git trailer keys are case-insensitive
        if key not in trailers:
            trailers[key] = m.group(2).strip()
            last = key
        else:
            last = None
    return trailers


def commits(root: Path, rev: str = "HEAD") -> list[Commit]:
    """Commits reachable from rev, oldest first."""
    try:
        git(root, "rev-parse", "--verify", "--quiet", rev)
    except TrackError:
        return []
    raw = git(
        root, "log", "--reverse", "--topo-order", "--date=short",
        "--format=%H%x1f%P%x1f%ad%x1f%s%x1f%B%x1e", rev,
    )
    result = []
    for rec in raw.split("\x1e"):
        rec = rec.strip("\n")
        if not rec:
            continue
        sha, parents, date, subject, body = rec.split("\x1f", 4)
        result.append(Commit(sha, date, subject, body, parents.split(), parse_trailers(body)))
    return result


def head(root: Path) -> str | None:
    try:
        return git(root, "rev-parse", "HEAD").strip()
    except TrackError:
        return None


@dataclass
class PushInfo:
    pushed: set[str]
    on_main: dict[str, str]  # sha -> "✓" or "✓ (PR #n)"


def push_info(root: Path) -> PushInfo:
    pushed = set(git(root, "rev-list", "--remotes=origin").split())
    on_main: dict[str, str] = {}
    try:
        main_commits = git(root, "rev-list", "origin/main").split()
    except TrackError:
        main_commits = []
    for sha in main_commits:
        on_main[sha] = "✓"
    if main_commits:
        merges = git(root, "log", "--first-parent", "--merges", "--format=%H %P%x1f%s", "origin/main")
        for line in merges.splitlines():
            ids, _, subject = line.partition("\x1f")
            parts = ids.split()
            pr = re.search(r"#(\d+)", subject)
            if len(parts) < 3 or not pr:
                continue
            for sha in git(root, "rev-list", f"{parts[1]}..{parts[2]}").split():
                on_main[sha] = f"✓ (PR #{pr.group(1)})"
    return PushInfo(pushed, on_main)


def attribution_hit(message: str) -> str | None:
    cleaned = message
    for allowed in ATTRIBUTION_ALLOWED:
        cleaned = cleaned.replace(allowed, "")
    m = ATTRIBUTION.search(cleaned)
    return m.group(0) if m else None


def subject_ok(subject: str, tid: str) -> bool:
    return tid == "meta" or subject.startswith(f"{tid}: ")


def kickoff_index(history: list[Commit]) -> int | None:
    for i, c in enumerate(history):
        if "Task" in c.trailers:
            return i
    return None


# ------------------------------------------------------------- generation


def esc(text: str) -> str:
    return text.replace("|", "\\|").replace("\n", " ")


def bar(done: int, total: int, width: int = 10) -> str:
    filled = round(width * done / total) if total else 0
    return "▓" * filled + "░" * (width - filled)


def counts(tasks: list[Task]) -> tuple[int, int]:
    live = [t for t in tasks if not t.status.startswith("dropped")]
    return sum(t.status == "done" for t in live), len(live)


def stage_position(batch: Batch) -> int:
    for i, s in enumerate(batch.stages, 1):
        d, n = counts(s.tasks)
        if d < n:
            return i
    return len(batch.stages)


def deps_done(plan: Plan, task: Task) -> bool:
    for dep in task.depends:
        if TASK_ID.match(dep):
            pool = [t for t in plan.tasks if t.id == dep]
        elif STAGE_ID.match(dep):
            pool = [t for t in plan.tasks if t.stage == dep]
        elif BATCH_ID.match(dep):
            pool = next((b.tasks for b in plan.batches if b.id == dep), [])
        else:
            return False
        if any(t.status not in ("done",) and not t.status.startswith("dropped") for t in pool):
            return False
    return True


def next_task(plan: Plan) -> Task | None:
    return next((t for t in plan.tasks if t.status == "todo" and deps_done(plan, t)), None)


def latest_verdict(b: Batch) -> str | None:
    """The latest 'Cross-check <batch>: <verdict>' note, upper-cased."""
    verdicts = [
        m.group(1).strip().upper()
        for note in b.notes
        if (m := re.search(rf"Cross-check {re.escape(b.id)}: (.+)$", note))
    ]
    return verdicts[-1] if verdicts else None


def next_cross_check(plan: Plan) -> str:
    """The auditor runs at every batch end (AGENT_PROMPT, 'When to remind me
    to cross-check'); its verdict is recorded as a 'Cross-check' line in the
    batch's Notes. Other triggers are event-driven and not derivable here."""
    for b in plan.batches:
        if not b.tasks:
            continue
        extra = " (+ second AI model's opinion)" if b.id in SECOND_OPINION else ""
        d, n = counts(b.tasks)
        if d < n:
            return f"at the end of {b.id} {b.name}{extra}"
        verdict = latest_verdict(b)
        if verdict and verdict.startswith("APPROVE WITH CONDITIONS"):
            return f"**{b.id} {b.name}: conditions open**; answer the auditor's conditions, then record APPROVE"
        if verdict is None or verdict.startswith("HOLD"):
            return f"**due now: {b.id} {b.name} is done**{extra}; send your auditor chat \"cross-check {b.id}\""
    return "none"


def banner(title: str, base: str | None) -> list[str]:
    at = base if base else "(no commits)"
    short = base[:7] if base else "none"
    return [
        f"{GENERATED_MARK}{at} -->",
        f"# {title}",
        "",
        f"> Generated by `tools/track.py sync` at commit `{short}`. Do not edit; run `python3 tools/track.py sync`.",
        "",
    ]


def push_cells(c: Commit, info: PushInfo | None) -> tuple[str, str]:
    if info is None:
        return EMPTY, EMPTY
    return ("✓" if c.sha in info.pushed else "✗"), info.on_main.get(c.sha, "✗")


def gen_status(plan: Plan, history: list[Commit], base: str | None, info: PushInfo | None) -> str:
    out = banner("md3 status", base)
    doing = [t for t in plan.tasks if t.status == "doing"]
    nxt = next_task(plan)
    out.append("## Position")
    out.append("")
    if doing:
        t = doing[0]
        b = next(b for b in plan.batches if any(x.id == t.id for x in b.tasks))
        d, n = counts(b.tasks)
        out.append(f"- Doing: **{t.id}** {t.name} ({b.id} stage {stage_position(b)} / {len(b.stages)}, {d} / {n} tasks)")
    else:
        out.append("- Doing: none")
    out.append(f"- Next: {f'**{nxt.id}** {nxt.name}' if nxt else 'none'}")
    out.append(f"- Next cross-check: {next_cross_check(plan)}")
    d, n = counts(plan.tasks)
    out.append(f"- Overall: {bar(d, n)} {d} / {n} tasks")
    out.append("")
    out.append("## Progress")
    out.append("")
    out.append("| Batch / stage | Progress | Done |")
    out.append("|---|---|---|")
    for b in plan.batches:
        d, n = counts(b.tasks)
        out.append(f"| **{b.id} {esc(b.name)}** | {bar(d, n)} | {d} / {n} |")
        for s in b.stages:
            d, n = counts(s.tasks)
            out.append(f"| {s.id} {esc(s.name)} | {bar(d, n)} | {d} / {n} |")
    out.append("")
    out.append("## Blockers")
    out.append("")
    blocked = [t for t in plan.tasks if t.status.startswith("blocked")]
    out += [f"- {t.id} {t.name}: {t.status[len('blocked: '):]}" for t in blocked] or ["none"]
    out.append("")
    out.append("## Last 10 commits")
    out.append("")
    out.append("| Date | Commit | Task | Subject | Pushed | On main |")
    out.append("|---|---|---|---|---|---|")
    for c in reversed(history[-10:]):
        p, m = push_cells(c, info)
        out.append(f"| {c.date} | {c.short} | {c.trailers.get('Task', EMPTY)} | {esc(c.subject)} | {p} | {m} |")
    return "\n".join(out) + "\n"


def gen_timeline(plan: Plan, history: list[Commit], base: str | None, info: PushInfo | None) -> str:
    out = banner("md3 timeline", base)
    start = kickoff_index(history)
    tracked = [c for c in history[start:]] if start is not None else []
    by_task: dict[str, list[Commit]] = {}
    other: list[Commit] = []
    for c in tracked:
        tid = c.trailers.get("Task")
        if tid and plan.task(tid):
            by_task.setdefault(tid, []).append(c)
        elif tid:
            other.append(c)
    header = ["| Date | Commit | Task | What was done | Evidence | Pushed | On main |", "|---|---|---|---|---|---|---|"]

    def row(c: Commit) -> str:
        p, m = push_cells(c, info)
        ev = esc(c.trailers.get("Evidence", "")) or EMPTY
        what = c.subject.removeprefix(f"{c.trailers['Task']}: ")
        return f"| {c.date} | {c.short} | {c.trailers['Task']} | {esc(what)} | {ev} | {p} | {m} |"

    order = {c.sha: i for i, c in enumerate(tracked)}
    for b in reversed(plan.batches):
        stage_rows = []
        for s in b.stages:
            cs = sorted((c for t in s.tasks for c in by_task.get(t.id, [])), key=lambda c: order[c.sha])
            if cs:
                stage_rows.append((s, cs))
        if not stage_rows:
            continue
        d, n = counts(b.tasks)
        out.append(f"## {b.id} {b.name} — stage {stage_position(b)} / {len(b.stages)} · {d} / {n} tasks")
        for s, cs in stage_rows:
            out.append(f"### {s.id} {s.name}")
            out += header
            out += [row(c) for c in cs]
            out.append("")
    if other:
        out.append("## Housekeeping and backlog")
        out += header
        out += [row(c) for c in other]
        out.append("")
    if not by_task and not other:
        out.append("No tracked commits yet.")
        out.append("")
    return "\n".join(out).rstrip("\n") + "\n"


def normalise(text: str) -> str:
    """Blank the push-state columns, which depend on the remote, not the repo."""
    out = []
    cols: list[int] = []
    for line in text.splitlines():
        if line.startswith("|"):
            cells = split_row(line)
            if "Pushed" in cells:
                cols = [cells.index("Pushed"), cells.index("On main")]
            elif cols and not set("".join(cells)) <= {"-"}:
                for i in cols:
                    if i < len(cells):
                        cells[i] = EMPTY
                line = "| " + " | ".join(cells) + " |"
        else:
            cols = []
        out.append(line)
    return "\n".join(out) + "\n"


def generated_base(text: str) -> str | None:
    first = text.splitlines()[0] if text else ""
    if not first.startswith(GENERATED_MARK):
        return None
    return first[len(GENERATED_MARK):].split(" ")[0]


# ---------------------------------------------------------------- check


def check(root: Path, pre_commit: bool = False) -> list[str]:
    """All tracking rules. pre_commit=True skips "done task has a commit",
    because the commit that finishes a task doesn't exist yet when the
    pre-commit hook runs; the commit-msg hook checks that one instead."""
    plan = parse_plan(root)
    errors = list(plan.errors)
    decisions = decision_index(root)

    seen: dict[str, str] = {}
    all_stage_ids = {s.id for b in plan.batches for s in b.stages}
    all_task_ids = {t.id for t in plan.tasks}
    for t in plan.tasks:
        where = f"{t.file}:{t.line}"
        if not TASK_ID.match(t.id) or not t.id.startswith(t.stage + "."):
            errors.append(f"{where}: malformed task ID '{t.id}' (must be {t.stage}.<n>)")
        if t.id in seen:
            errors.append(f"{where}: duplicate task ID {t.id} (also {seen[t.id]})")
        seen[t.id] = where
        if not STATUS_RE.match(t.status):
            errors.append(f"{where}: {t.id} has invalid status '{t.status}'")
        for ref in decision_refs(t.decisions):
            if ref.startswith("#") and ref[1:] in decisions.superseded:
                errors.append(f"{where}: {t.id} cites {ref}, which is superseded (⛔) in {DECISIONS}")
            elif not decision_exists(ref, decisions.active, decisions.text):
                errors.append(f"{where}: {t.id} cites {ref}, not found in {DECISIONS}")
        for dep in t.depends:
            known = (
                dep in all_task_ids
                or dep in all_stage_ids
                or any(b.id == dep for b in plan.batches)
            )
            if not known:
                errors.append(f"{where}: {t.id} depends on unknown '{dep}'")
    doing = [t.id for t in plan.tasks if t.status == "doing"]
    if len(doing) > 1:
        errors.append(f"more than one task is doing: {', '.join(doing)}")

    if git(root, "rev-parse", "--is-shallow-repository").strip() == "true":
        errors.append("shallow clone: track.py needs full history (CI: actions/checkout with fetch-depth: 0)")
        return errors
    history = commits(root)
    for c in history:
        hit = attribution_hit(c.message)
        if hit:
            errors.append(f"commit {c.short}: AI attribution in message ('{hit}'); security rule 10")
    start = kickoff_index(history)
    tracked = history[start:] if start is not None else []
    task_commits: dict[str, list[Commit]] = {}
    for c in tracked:
        if c.is_merge:
            continue
        tid = c.trailers.get("Task")
        if tid is None:
            errors.append(f"commit {c.short} '{c.subject}': missing Task: trailer")
            continue
        if not (tid == "meta" or tid in all_task_ids or (X_ID.match(tid) and tid in plan.backlog_ids)):
            errors.append(f"commit {c.short}: Task: {tid} is not a task ID, a backlog X ID or 'meta'")
            continue
        if not subject_ok(c.subject, tid):
            errors.append(f"commit {c.short}: subject must start with '{tid}: '")
        task_commits.setdefault(tid, []).append(c)
    for t in plan.tasks:
        if t.status != "done" or pre_commit:
            continue
        cs = task_commits.get(t.id, [])
        if not cs:
            errors.append(f"{t.file}:{t.line}: {t.id} is done but no commit has 'Task: {t.id}'")
        elif not any("Evidence" in c.trailers for c in cs):
            errors.append(f"{t.file}:{t.line}: {t.id} is done but none of its commits has an Evidence: trailer")

    errors += check_generated(root, plan)
    errors += check_no_ebu_files(root)
    return errors


# #176: the official EBU loudness test files may not be redistributed, so
# they must never be committed. Matches audio named after Tech 3341/3342
# and the EBU zip's folder; mirrored in .gitignore.
EBU_FILE = re.compile(
    r"(^|/)[^/]*(3341|3342)[^/]*\.(wav|wave|bwf|aif|aiff|flac)$|(^|/)ebu-loudness-test-set",
    re.IGNORECASE,
)


def check_no_ebu_files(root: Path) -> list[str]:
    tracked = git(root, "ls-files", "-z").split("\0")
    return [
        f"{path}: looks like an official EBU test file; these must never be committed (#176)"
        for path in tracked
        if path and EBU_FILE.search(path)
    ]


def read_plain(path: Path) -> str:
    """Read a tracked text file, refusing symlinks (a PR could point one
    anywhere on the machine that runs the check)."""
    if path.is_symlink():
        raise TrackError(f"{path} is a symlink; tracking files must be regular files")
    return path.read_text(encoding="utf-8")


def check_generated(root: Path, plan: Plan) -> list[str]:
    errors = []
    current = head(root)
    for path, gen in ((STATUS, gen_status), (TIMELINE, gen_timeline)):
        f = root / path
        if f.is_symlink():
            errors.append(f"{path} is a symlink; it must be a regular generated file")
            continue
        if not f.exists():
            errors.append(f"{path} missing; run tools/track.py sync")
            continue
        text = f.read_text(encoding="utf-8")
        base = generated_base(text)
        if base is None:
            errors.append(f"{path} has no generated banner; run tools/track.py sync")
            continue
        if base != "(no commits)" and not re.fullmatch(r"[0-9a-f]{40}", base):
            errors.append(f"{path} has a malformed generated banner; run tools/track.py sync")
            continue
        if base == "(no commits)":
            base_ok = current is None
            base = None
        else:
            base_ok = current is not None and allowed_base(root, base, current)
        if not base_ok:
            errors.append(
                f"{path} was generated at {base[:7] if base else 'no commit'}, which is stale "
                "(after an amend or rebase the hook's base commit is gone): run tools/track.py sync "
                "and commit the result; prefer a new commit over --amend"
            )
            continue
        expected = gen(plan, commits(root, base) if base else [], base, None)
        if normalise(text) != normalise(expected):
            errors.append(f"{path} does not match the batch files and git; run tools/track.py sync")
    return errors


def check_message(root: Path, text: str) -> list[str]:
    """Rules for one commit message (the commit-msg hook)."""
    lines = []
    for line in text.splitlines():
        if line.startswith("# ------------------------ >8"):
            break
        if not line.startswith("#"):
            lines.append(line)
    message = "\n".join(lines).strip()
    errors = []
    hit = attribution_hit(message)
    if hit:
        errors.append(f"AI attribution in message ('{hit}'); security rule 10")
    git_dir = Path(git(root, "rev-parse", "--absolute-git-dir").strip())
    if (git_dir / "MERGE_HEAD").exists():
        return errors
    subject = message.splitlines()[0] if message else ""
    if len(subject) > 72:
        errors.append(f"subject is {len(subject)} characters; max 72")
    plan = parse_plan(root)
    tid = parse_trailers(message).get("Task")
    if tid is None:
        errors.append("missing Task: trailer (task ID, backlog X ID or 'meta')")
        return errors
    task = plan.task(tid)
    if not (tid == "meta" or task or (X_ID.match(tid) and tid in plan.backlog_ids)):
        errors.append(f"Task: {tid} is not a task ID, a backlog X ID or 'meta'")
        return errors
    if not subject_ok(subject, tid):
        errors.append(f"subject must start with '{tid}: '")
    if task and task.status == "done" and "Evidence" not in parse_trailers(message):
        earlier = [c for c in commits(root) if c.trailers.get("Task") == tid and "Evidence" in c.trailers]
        if not earlier:
            errors.append(f"{tid} is marked done, so this commit needs an Evidence: trailer")
    return errors


def allowed_base(root: Path, base: str, current: str) -> bool:
    """The generated files may lag HEAD by the commit that contains them
    (the pre-commit hook runs before the commit exists) and by merge commits
    made on GitHub, which don't run the hook."""
    if base == current:
        return True
    try:
        git(root, "merge-base", "--is-ancestor", base, current)
    except TrackError:
        return False
    revs = [f"{base}..{current}"]
    parents = git(root, "rev-list", "--parents", "-n", "1", current).split()[1:]
    if len(parents) > 1:  # a merge: ignore what main already had
        revs += ["--not", parents[0]]
    newer = [line.split() for line in git(root, "rev-list", "--parents", *revs).splitlines()]
    plain = [ids for ids in newer if len(ids) == 2]
    # At most one ordinary commit: the one the hook generated the files for.
    return not plain or (len(plain) == 1 and plain[0][1] == base)


# ------------------------------------------------------------- commands


def sync(root: Path, info: PushInfo | None = None) -> None:
    plan = parse_plan(root)
    base = head(root)
    history = commits(root)
    for path in (STATUS, TIMELINE):
        if (root / path).is_symlink():
            raise TrackError(f"{path} is a symlink; refusing to write through it")
    (root / STATUS).write_text(gen_status(plan, history, base, info), encoding="utf-8")
    (root / TIMELINE).write_text(gen_timeline(plan, history, base, info), encoding="utf-8")


def safe_push_info(root: Path) -> PushInfo | None:
    try:
        return push_info(root)
    except TrackError:
        return None


def report(root: Path, fetch: bool = True) -> str:
    if fetch:
        try:
            subprocess.run(["git", "fetch", "--quiet", "origin"], cwd=root, capture_output=True, timeout=20)
        except subprocess.TimeoutExpired:
            print("track.py report: fetch timed out; push state may be out of date", file=sys.stderr)
    plan = parse_plan(root)
    history = commits(root)
    info = safe_push_info(root)
    text = gen_status(plan, history, head(root), info)
    lines = [l for l in text.splitlines() if not l.startswith(GENERATED_MARK) and not l.startswith("> Generated")]
    if info is not None and history:
        unpushed = [c for c in history if c.sha not in info.pushed]
        lines.insert(2, f"> Live: HEAD `{history[-1].short}` · {len(unpushed)} commit(s) not pushed")
    return "\n".join(lines).strip() + "\n"


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("command", choices=["check", "sync", "report", "next", "msg"])
    ap.add_argument("file", nargs="?", help="msg: the commit message file")
    ap.add_argument("--pre-commit", action="store_true", help="check: run as the pre-commit hook")
    ap.add_argument("--root", default=None, help="repository root (default: from git)")
    ap.add_argument("--no-fetch", action="store_true", help="report: don't fetch origin")
    args = ap.parse_args(argv)
    root = Path(args.root) if args.root else Path(
        subprocess.run(["git", "rev-parse", "--show-toplevel"], capture_output=True, text=True).stdout.strip() or "."
    )
    try:
        if args.command == "check":
            errors = check(root, pre_commit=args.pre_commit)
            for e in errors:
                print(f"✗ {e}", file=sys.stderr)
            if errors:
                print(f"track.py check: {len(errors)} problem(s)", file=sys.stderr)
                return 1
            print("track.py check: ok")
        elif args.command == "msg":
            if not args.file:
                ap.error("msg needs the commit message file")
            errors = check_message(root, Path(args.file).read_text(encoding="utf-8"))
            for e in errors:
                print(f"✗ commit message: {e}", file=sys.stderr)
            if errors:
                print("Format: '<task ID>: <subject>', blank line, body, blank line, trailers (Task:, Decisions:, Evidence:). See docs/plan/README.md.", file=sys.stderr)
                return 1
        elif args.command == "sync":
            sync(root, safe_push_info(root))
            print(f"track.py sync: wrote {STATUS} and {TIMELINE}")
        elif args.command == "report":
            print(report(root, fetch=not args.no_fetch), end="")
        elif args.command == "next":
            t = next_task(parse_plan(root))
            print(f"{t.id} {t.name}" if t else "No todo task has all its dependencies done.")
    except TrackError as e:
        print(f"track.py: {e}", file=sys.stderr)
        return 2
    return 0


if __name__ == "__main__":
    sys.exit(main())
